version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: inium/php:7.4.4-fpm
    container_name: php
    hostname: php
    environment:
      - DOCKER_ENV=development
    ports:
      - "10000:80"
    volumes:
      - ./html:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    network_mode: bridge
