version: "3"

services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1.0
    image: apache2-php7:latest
    container_name: web
    hostname: web
    depends_on: 
      - db
    ports: 
      - "10000:80"
    volumes: 
      - ".:/var/www/html"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on: 
      - db
    # external_links: 
    #   - "db:db"
    ports: 
      - "8080:80"

  db:
    image: mariadb:latest
    container_name: db
    environment: 
      # $$ for escaping of $: convert $$ to $
      - MYSQL_ROOT_PASSWORD=on1yforTe$$t  # passowrd: on1yforTe$t
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=myPa$$sw0rd        # password: mYpas$w0rd

